CHANGELOG.EN.md, CHANGELOG.ZH.md, src/i18n/zh.js, src/views/equipment_management/editdevices.vue
=> feat: echatrts adaptive

CHANGELOG.EN.md, CHANGELOG.ZH.md, src/vab/components/VabLogo/index.vue
=> style(src/vab/components/vablogo/index.vue): icon style

CHANGELOG.EN.md, CHANGELOG.ZH.md, src/api/License/index.js, src/api/Project/index.js, src/store/modules/user.js, src/views/login/index.vue, src/views/user/userinfo.vue
=> feat(src/views/login/index.vue): img bug fix

.github/workflows/sync-repo.yml
=> feat: sync yml

src/api/Global/device.js, src/components/Device/deviceState.vue, src/store/modules/global.js, src/utils/swagger/index.js, src/utils/utilwen.js, src/utils/vuex.js, src/vab/components/VabEmpty/index.vue, src/views/engine/addengine.vue, src/views/equipment_management/home_index.vue
fix(src/views/engine/addengine.vue): resources bind key
=> fix(src/views/engine/addengine.vue): resources bind key

src/views/Maintenance/index.vue, src/views/Maintenance/myticket.vue
feat(maintenance myticket): myticket page
=> feat(maintenance myticket): myticket page

src/api/File/index.js, src/i18n/zh.js, src/store/modules/websocket.js, src/vab/components/VabParser/index.vue, src/views/Maintenance/components/Step1.vue, src/views/Maintenance/components/Step2.vue, src/views/Maintenance/components/Step3.vue, src/views/Maintenance/components/Step4.vue, src/views/Maintenance/myticket.vue, src/views/equipment_management/editdevices.vue, src/views/equipment_management/home_group2.vue, src/views/equipment_management/home_index.vue, src/views/equipment_management/platform_overview.vue, src/views/equipment_management/proddetail.vue, src/views/tools/player.vue, src/views/user/userinfo.vue
=> feat: custom form

src/vab/components/VabPagination/index.vue, src/views/Maintenance/index.vue, src/views/Maintenance/myticket.vue, src/views/engine/rulesengine.vue, src/views/equipment_management/proddetail.vue, src/views/roles/rolelist/rolescontrol.vue
Repair ticket cannot be created successfully
=> Repair ticket cannot be created successfully

src/store/modules/settings.js, src/vab/components/VabLogo/index.vue, src/vab/styles/variables/variables.scss, src/views/equipment_management/index.vue, src/views/topo/components/TopoAllocation.vue
=> feat: logo theme style

Dockerfile
build(dockerfile): docker use yarn
=> build(dockerfile): docker use yarn

Dockerfile
feat(dockerfile): docker config
=> feat(dockerfile): docker config

Dockerfile
=> feat: docker config

Dockerfile, public/index.html, src/config/cdn.config.js, src/i18n/zh.js, src/store/modules/user.js, src/views/engine/home_resourcechannel.vue, src/views/equipment_management/profile.vue, src/views/login/index.vue, src/views/platform/testpumplist/modelmanage.vue, src/views/roles/rolelist/rolescontrol.vue
feat: login interface optimization
=> feat: login interface optimization

src/api/Acl/index.js, src/store/modules/settings.js, src/store/modules/user.js, src/utils/utilwen.js, src/vab/components/VabTheme/components/VabThemeDrawer.vue, src/views/Maintenance/myticket.vue, src/views/equipment_management/component/wmxdetail.vue, src/views/equipment_management/home_index.vue, src/views/equipment_management/platform_overview.vue, src/views/equipment_management/proddetail.vue
=> feat: query optimization

public/index.html, src/assets/data/form-item-common.js, src/config/cdn.config.js, src/store/modules/frender.js, src/vab/components/VabParser/index.vue, src/vab/components/VabRender/components/left/index.vue, src/vab/components/VabRender/components/main/components/batch-dialog.vue, src/vab/components/VabRender/components/main/components/code-dialog.vue, src/vab/components/VabRender/components/main/components/data-dialog.vue, src/vab/components/VabRender/components/main/components/preview-dialog.vue, src/vab/components/VabRender/components/main/components/tpl/vab-render.js, src/vab/components/VabRender/components/main/index.vue, src/vab/components/VabRender/components/main/main-content.vue, src/vab/components/VabRender/components/main/main-header.vue, src/vab/components/VabRender/components/right/components/attrs-header.vue, src/vab/components/VabRender/components/right/components/form-item-rules.vue, src/vab/components/VabRender/components/right/form-item-attrs.vue, src/vab/components/VabRender/components/right/form-item-common.vue, src/vab/components/VabRender/components/right/form-props.vue, src/vab/components/VabRender/components/right/index.vue, src/vab/components/VabRender/global-components.js, src/vab/components/VabRender/index.js, src/vab/components/VabRender/index.vue, src/vab/styles/loading.scss, src/vab/styles/vab.scss, src/views/equipment_management/home_group2.vue, src/views/equipment_management/profile.vue, vue.config.js
feat: dynamic form related object model and dictionary
=> feat: dynamic form related object model and dictionary

.github/release-drafter.yml, .github/workflows/release-drafter.yml, .github/workflows/release.yml, package.json, scripts/replaceVersion.js, yarn.lock
=> feat: build release

.github/workflows/release.yml
ci(script command): script command
=> ci(script command): script command

package.json, src/api/Export/index.js, src/views/equipment_management/parse.vue
=> package.json

CHANGELOG.EN.md, CHANGELOG.ZH.md, package.json, src/api/Article/index.js, src/api/Doc/index.js, src/config/cdn.config.js, src/i18n/zh.js, src/store/modules/global.js, src/vab/components/VabEmpty/index.vue, src/vab/components/VabVditor/index.vue, src/views/Doc/components/details.vue, src/views/Doc/components/module/docDialog.vue, src/views/Doc/index.vue, src/views/equipment_management/home_group2.vue, src/views/equipment_management/home_index.vue, src/views/equipment_management/platform_overview.vue, src/views/equipment_management/profile.vue, src/views/ota/index.vue, src/views/platform/testpumplist/modelmanage.vue, src/views/topo/VueKonva.vue, src/views/topo/components/TopoBase.vue, src/views/topo/components/iconfont.json, src/views/topo/index.vue
=> feat: dgiot doc

src/i18n/zh.js, src/vab/components/VabHelp/index.vue, src/vab/directives/package/copy.js, src/vab/directives/package/copyText.js, src/views/Logs/access.vue, src/views/Logs/history.vue, src/views/Logs/index.vue, src/views/equipment_management/home_group2.vue, src/views/topo/components/TopoAllocation.vue, src/views/topo/components/TopoBase.vue, src/views/topo/components/TopoOperation.vue, src/views/topo/components/topoHeader.vue, src/views/topo/index.vue
1. logle table 
2. konva header 
3. utils
=> feat(src/views/logs/*): log table

.github/workflows/ubuntu-latest.yml
=> ci(action): .github/workflows/ubuntu-latest.yml

package.json
=> chore(deps): update dependency eslint to v8

package.json
=> chore(deps): update dependency vue-eslint-parser to v8

package.json
=> chore(deps): update dependency eslint-plugin-vue to v8

.eslintrc.js, .github/workflows/ubuntu-latest.yml, package.json, pnpm-lock.yaml
=> chore(.eslintrc.js): devDependencies

src/views/DeviceCloud/manage/js/proddetail.js
=> feat: save json type

src/views/DeviceCloud/manage/js/proddetail.js, src/views/DeviceCloud/manage/proddetail.vue
=> feat(thing): 优化物模型删除刷新

src/dgiot/components/DgiotAmis/render.vue, src/dgiot/components/DgiotJsonEditor/index.vue, src/dgiot/directives/package/assets/waves.css, src/dgiot/styles/default.scss, src/dgiot/styles/loading/dots.css, src/dgiot/styles/themes/blue-black.scss, src/dgiot/styles/themes/element-green.scss, src/dgiot/styles/themes/green-black.scss, src/dgiot/styles/themes/red-black.scss, src/dgiot/styles/themes/red.scss, src/dgiot/styles/variables/element-variables.scss, src/dgiot/styles/variables/variables.scss, src/views/DeviceCloud/manage/js/proddetail.js
=> fix: 修复打包编译失败

src/dgiot/directives/package/focus.js, src/dgiot/filters/package/statusFilter.js, src/views/CloudFunction/engine/channel.vue, src/views/CloudFunction/lowcode/index.vue, src/views/DeviceCloud/manage/home_index.vue
=> feat(device): device table

src/views/CloudFunction/lowcode/components/ViewEdit.vue, src/views/CloudFunction/lowcode/index.vue
=> feat: lowcode(from select)

src/views/CloudFunction/lowcode/components/ViewEdit.vue, src/views/CloudSystem/manage/appmarage.vue
#
Fixes #418 https://github.com/dgiot/dgiot/issues/446
=> fix https://github.com/dgiot/dgiot/issues/446

src/views/CloudFunction/engine/channel.vue, src/views/CloudFunction/lowcode/index.vue, src/views/DeviceCloud/manage/index.vue, src/views/DeviceCloud/manage/productTemplet.vue
fix https://gitee.com/dgiiot/dgiot/issues/I59CVB
=> fix(delete channel): channel

pnpm-lock.yaml, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/js/proddetail.js
=> feat(thing): message

src/views/CloudFunction/engine/channel.vue, src/views/DeviceCloud/manage/platform_overview.vue
#fix https://github.com/dgiot/dgiot/issues/447
fix https://github.com/dgiot/dgiot/issues/447
=> fix(channel message)

src/views/CloudFunction/lowcode/index.vue, src/views/CloudPressure/index.vue, src/views/DeviceCloud/manage/platform_overview.vue
fix https://github.com/dgiot/dgiot/issues/448
=> fix(table): table height

.github/workflows/deploy.yml, src/api/Dlink/index.js
=> ci(action): user yarn

package.json, public/index.html, src/views/DeviceCloud/manage/platform_overview.vue, src/views/MultiTenant/user/login/index.vue
=> feat(home): topic Back end subscription homepage topic

.cz-config.js, package.json
=> docs(package.json): commit-msg

package.json, src/api/Article/index.js, src/api/Dlink/index.js, src/config/local.config.js, src/dgiot/components/DgiotVditor/index.vue, src/main.js, src/views/CloudFunction/doc/components/details.vue, src/views/CloudFunction/doc/components/index.vue, src/views/CloudFunction/doc/components/module/docDialog.vue, src/views/CloudFunction/doc/index.vue, src/views/CloudFunction/engine/channel.vue, src/views/CloudFunction/engine/components/mqttLog.vue, src/views/CloudFunction/topo/VueKonva.vue, src/views/CloudFunction/topo/index.vue, src/views/CloudFunction/topo/topo.vue, src/views/CloudSystem/manage/appmarage.vue, src/views/CloudTest/js/task.js, src/views/DeviceCloud/manage/component/SceneLog.vue, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/js/devicesDetailLite.js, src/views/DeviceCloud/manage/js/editdevices.js, src/views/DeviceCloud/manage/js/proddetail.js
=> feat(文档): 完成文档功能

src/views/CloudPressure/grafana.vue, src/views/CloudPressure/index.vue
=> feat(grafana): url

src/views/CloudPressure/index.vue
=> fix(queryZetaProduct): queryProductTemplet

src/config/setting.config.js, src/store/modules/routes.js, src/utils/router/utils.js, src/views/CloudPressure/index.vue
=> feat(router): 路由处理分离

src/utils/index.js, src/views/CloudFunction/topo/preview.vue
=> feat: knova Configuration display

package.json, src/views/CloudFunction/lowcode/index.vue, src/views/CloudPressure/index.vue
=> feat(低代码): 修复低代码链接跳转

.github/workflows/sync.yml
=> fix(action): 修复sync工作流语法不正确

src/views/CloudPressure/index.vue
=> fix(压测报告): 修复压测列表样式错乱的问题

.cz-config.js, src/views/DeviceCloud/manage/devicelist.vue
=> feat(projects): 设备迁移后刷新列表

src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
=> fix(components): 修复topic 订阅不正常

src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
=> fix(other): 修复设备列表参数不更新

src/dgiot/components/DgiotBaiduMap/index.vue, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/devicesDetailLite.vue, src/views/DeviceCloud/manage/editdevices.vue, src/views/DeviceCloud/manage/home_index.vue
=> feat(components): 百度地图

src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
=> feat(other): 设备管理

.cz-config.js, package.json, src/dgiot/components/DgiotHeader/index.vue, src/dgiot/components/DgiotNav/index.vue, src/main.js, src/utils/request/request.js, src/views/CloudFunction/doc/components/details.vue, src/views/CloudFunction/doc/components/index.vue, src/views/CloudFunction/doc/index.vue, src/views/CloudFunction/lowcode/components/ViewEdit.vue, src/views/CloudFunction/lowcode/index.vue, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
修复界面管理传值问题
BREAKING CHANGE:
https://github.com/dgiot/dgiot/issues/486
ISSUES CLOSED: https://github.com/dgiot/dgiot/issues/486
=> fix(issues): 界面管理

.husky/pre-push, CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, package.json
=> feat(deps): scripts

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, package.json, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
=> feat(components): 设备管理 

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
=> fix(other): 修復设备列表订阅

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
=> fix(components): 设备列表 

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/views/CloudPressure/grafana.vue, src/views/DeviceCloud/manage/devicelist.vue, src/views/DeviceCloud/manage/home_index.vue
=> fix(components): 设备列表

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/views/DeviceCloud/manage/js/proddetail.js
=> fix(components): 百度地图

.github/dependabot.yml, CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/dgiot/components/DgiotAmis/render.vue, src/views/DeviceCloud/manage/js/proddetail.js
=> fix(equipmentCloud): 修复产品详情默认经纬度未赋值导致的报错

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, public/index.html
=> feat(统计功能): 添加友盟统计

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/dgiot/components/DgiotThreeCheckbox/index.vue, src/views/DeviceCloud/manage/home_index.vue, src/views/DeviceCloud/manage/js/editdevices.js
=> feat(dashboard): 更新设备管理参数条件

src/dgiot/components/DgiotDoc/index.vue, src/dgiot/components/DgiotHeader/index.vue, src/dgiot/components/DgiotNav/index.vue, src/views/DeviceCloud/manage/component/wmxdetail.vue, src/views/DeviceCloud/manage/js/proddetail.js, src/views/DeviceCloud/manage/proddetail.vue
=> feat(equipmentCloud): 物模型是否展示

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/views/CloudOT/maintenance/myticket.vue, src/views/DeviceCloud/manage/component/wmxdetail.vue, src/views/DeviceCloud/manage/home_index.vue
=> feat(equipmentCloud): konva

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md, src/views/DeviceCloud/manage/proddetail.vue
=> feat(dashboard): feat(equipmentCloud): konva

src/views/CloudFunction/topo/components/Thing.vue, src/views/DeviceCloud/manage/component/wmxdetail.vue, src/views/DeviceCloud/manage/home_index.vue, src/views/DeviceCloud/manage/js/proddetail.js
=> fix(equipmentCloud): 组态

CHANGELOG.EN.md, CHANGELOG.ZH.md, CHANGELOG.md
=> fix(dashboard): build(发布版本): dgiot-dashboard@v4.5.6

src/store/modules/topo.js, src/store/modules/user.js, src/utils/konva/common.js, src/utils/konva/core/topoBasic.js, src/utils/konva/core/topoStage.js, src/views/CloudFunction/engine/channel.vue, src/views/CloudFunction/topo/components/TopoTabs.vue, src/views/CloudFunction/topo/index.vue, src/views/DeviceCloud/manage/component/topocompvue/TopoLine.vue, src/views/DeviceCloud/manage/home_index.vue, src/views/DeviceCloud/manage/konvadevice.vue
=> fix: konva cannot be edited

src/views/CloudFunction/lowcode/components/ViewEdit.vue, src/views/CloudFunction/lowcode/index.vue, src/views/MultiTenant/user/login/index.vue
=> fix: amis interface manage

src/api/MetaData/index.js, src/api/System/filemanagement.js, src/i18n/zh.js, src/utils/konva/common.js, src/views/CloudOc/OrderManage/index.vue, src/views/CloudSystem/manage/filemanagement.vue, src/views/DeviceCloud/manage/js/proddetail.js, src/views/DeviceCloud/manage/proddetail.vue
=> feat:file Manage

src/views/CloudOc/AmisPage/index.vue, src/views/DeviceCloud/manage/js/proddetail.js, src/views/MultiTenant/roles/list/addroles.vue
=> feat:amisPage add

src/api/Dlink/index.js, src/store/modules/topo.js, src/utils/konva/common.js, src/utils/konva/core/topoBasic.js, src/utils/konva/core/topoStage.js, src/views/CloudFunction/lowcode/components/ViewEdit.vue, src/views/CloudFunction/topo/components/TopoTabs.vue, src/views/CloudFunction/topo/index.vue, src/views/DeviceCloud/manage/platform_overview.vue, src/views/MultiTenant/roles/list/roles.vue
=> feat: topo
